[package]
name = "hyprwin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"] # Required to build a dynamic library that can be loaded by anyrun

[dependencies]
anyrun-plugin = { git = "https://github.com/Kirottu/anyrun" }
abi_stable = "0.11.1"
hyprland = "0.3.11"
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
ron = "0.8.1"
fuzzy-matcher = "0.3.7"
